name: Check format in /lib
on: push
jobs:
  check_format_in_lib:
    name: Check format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.2.3"
      - name: Check format
        run: ./scripts/format_and_check_lib.sh